### ISSUE TITLE
Implement the extensions searchbar

### ISSUE THREAD

**Issue by tomlin7** [tomlin7/biscuit#409]
Following #334 
The extension center search bar is not functional yet, simply implement this.
- [ ] When search bar is not empty, filter the extensions (from `extensions.toml`) and show the results
- [ ] When search bar is empty, show the recommend extensions (`recommended.toml` #334 )

**Comment by tomlin7** [comment]
Hello @Kabiirk 

This issue regarding the extensions view search bar is also connected to #334 (showing recommended extensions by default), which is not completed yet. So currently, the view shows all the extensions from [`extensions.toml`](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/extensions/extensions.py#L39) 
- This file is fetched [within extension manager](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/extensions/extensions.py#L117) 

After fetching the data is inserted into a fetch queue, and this is accessed in the [extensions GUI](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/views/extensions/results.py#L81) 

You will just have to filter the data according to the extensions search bar input and show it whenever the search bar is not empty.

**Comment by Kabiirk** [comment]
Ah, I see, so you are already populating the sidebar 'frame' (which shows the extension names). I just need to write the logic to filter from the given names (basically running a filter query on [self.fetch_queue](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/extensions/extensions.py#L139)) and update the GUI. 

I'd be happy to assist on this, Thanks for the detailed description & clarity !

**Comment by Kabiirk** [comment]
Hi @tomlin7, I'm working on [Issue#409](https://github.com/tomlin7/biscuit/issues/409) in biscuit. I've been facing issues in getting the project up and running 

Steps as per `contribution guidelines`:
1. I cloned the repo
2. I ran `poetry install` from root
3. when I try to run the application from root using `poetry run biscuit`, I get the following error :

> File "/mnt/c/users/..../Hacktoberfest/2024/biscuit/src/biscuit/common/icons.py", line 1, in <module>
>     from enum import StrEnum
> ImportError: cannot import name 'StrEnum' from 'enum' (/usr/lib/python3.10/enum.py)

I tried reinstalling enum (confirmed to be installed with `poetry run python3` then importing enum via  `import enum`) but it still doesnt solve the issue . I also tried reinstalling enum with `poetry run pip install enum` but I get the following error :
> Collecting enum
>   Using cached enum-0.4.7.tar.gz (20 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [8 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 11, in <module>
>         File "/usr/lib/python3.10/tokenize.py", line 33, in <module>
>           import re
>         File "/usr/lib/python3.10/re.py", line 145, in <module>
>           class RegexFlag(enum.IntFlag):
>       AttributeError: module 'enum' has no attribute 'IntFlag'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

**System info:**
Ubuntu 22.0 (WSL2) (I installed pre-requisites)
python version  : 3.10.12
poetry version : 1.8.4
biscuit repo branch : main (my fork is synced to the latest commit)

**Comment by tomlin7** [comment]
@Kabiirk thanks for bringing this to my attention! StrEnum wasn't added until 3.11, so that makes the editor support only Python 3.11+. Please try again with the mentioned version or try using a version manager like pyenv to handle both versions if you still need 3.10!

**Comment by Kabiirk** [comment]
hi @tomlin7,

Thanks for the support ! I was able to get the project up and running with **Python 3.11.9**

I have implemented the search functionality. It looks like this :
![screen-capture9-ezgif com-speed](https://github.com/user-attachments/assets/005fb235-ffef-4b25-9214-19ccbc65706d)

This has been achieved by adding search functions (filter logic) to the `ExtensionManager` in  `src\biscuit\extensions\extensions.py`

Let me know if this looks good. I'll make the PR

_____

**P.S.**
I found out the hard way that `Biscuit` doesn't build with latest version of Python (v3.13). Since the `cgi` subpackage in the `tarts` dependency is deprecated & removed in Python 3.13 [(source 1)](https://discuss.python.org/t/alternative-function-for-deprecated-cgi/21960) [(source 2)](https://docs.python.org/3.11/library/cgi.html) [(Source 3)](https://github.com/cherrypy/cherrypy/issues/2014). Alternatives for `cgi` methods are mentioned in the [docs](https://docs.python.org/3.11/library/cgi.html) itself.

This is more of a problem for devs @ `tarts` to solve. Only impact I see on this project is that it throws a `ModuleNotFoundError: No module named 'cgi'` when you run the project (`biscuit` or `poetry run biscuit`) after building with Python 3.13 & above.

**Comment by tomlin7** [comment]
@Kabiirk that looks excellent to me! please open a pr and I will merge it.
- It would be nice to trigger the search via the enter key press too

Btw thanks for pointing out the dependency error! I will mark Biscuit as unsupported for 3.13 until this issue is resolved. Tarts is maintained by me currently. I'll make some quick changes to fix this for now.

**Comment by Kabiirk** [comment]
@tomlin7 Done ! I've added the enter key-press functionality.

Making PR.
